### ISSUE TITLE
Add Branch Milestones to timeline

### ISSUE THREAD

**Issue by QAnalysts-Kirkland** [mozilla-b2g/b2g-dashboard#25]
I noticed some surges in activity to reflect Milestones (Aurora branching, b2g branching, etc).  This extra view would provide an additional layer of information to what we're looking at.

**Comment by JohanLorenzo** [comment]
Great! This should be doable by setting the milestones in a config file and then display it like this: http://c3js.org/samples/grid_x_lines.html.
